version: '2'

services:
   php:
    build: ./.docker/conf/php
    ports:
      - '80:80'
    restart: always
    environment:
        XDEBUG_CONFIG: remote_host=192.168.99.1
    volumes:
#       - ./.docker/images/php/error.log:/var/log/apache2/error.log
#       - ./.docker/images/php/access.log:/var/log/apache2/access.log
       - ./app:/var/www/html
